# SPDX-License-Identifier: Apache-2.0

FROM nvcr.io/nvidia/cuda:12.4.1-devel-ubi9
RUN dnf install -y python3.11 python3.11-devel git python3-pip make automake gcc gcc-c++
WORKDIR /home/ilabuser
RUN python3.11 -m ensurepip
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
RUN rpm -ivh https://us.download.nvidia.com/tesla/550.54.14/nvidia-driver-local-repo-rhel9-550.54.14-1.0-1.x86_64.rpm 
RUN dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo && dnf repolist && dnf config-manager --set-enabled cuda-rhel9-x86_64 && dnf config-manager --set-enabled cuda && dnf config-manager --set-enabled epel && dnf update -y
RUN dnf install -y libcudnn8 nvidia-driver-NVML-550.54.14-1.el9 nvidia-driver-cuda-libs-550.54.14-1.el9 

RUN dnf install -y pciutils

RUN python3.11 -m pip install --force-reinstall nvidia-cuda-nvcc-cu12
RUN export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64" \
    && export CUDA_HOME=/usr/local/cuda \
    && export PATH="/usr/local/cuda/bin:$PATH" \
    && export XLA_TARGET=cuda120 \
    && export XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/local/cuda \
	&& export HOME=/home/ilabuser

ARG GIT_TAG=stable
 
RUN useradd -ms /bin/bash -p "$(openssl passwd -1 ilabpwd)" ilabuser
USER ilabuser
WORKDIR /home/ilabuser

ARG USERNAME=ilabuser

RUN export HOME=/home/ilabuser

CMD ["/bin/bash"]

LABEL com.redhat.component="instructlab"